# Button pins
DANGER_BUTTON = 6
WEATHER_BUTTON = 13
POLLUTION_BUTTON = 19
NORIDE_REPORT_BUTTON = 26

# LED pins
DANGER_LED = 12
WEATHER_LED = 16
POLLUTION_LED = 20
DRIVING_LED = 21

# Vibration motor pin
VIBRATION_PIN = 1

# Humidity sensor data
DHT_PIN = 5

# Reset pin for ToF sensors
XSHUT_LEFT_PIN = 17
XSHUT_MIDDLE_PIN = 27
XSHUT_RIGHT_PIN = 22

# I2C addresses of ToF sensors
TOF_LEFT_ADDRESS = 0x2D
TOF_MIDDLE_ADDRESS = 0x2B
TOF_RIGHT_ADDRESS = 0x29
